// <auto-generated />
namespace RedBadgeFinalProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FkExpense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FkExpense));
        
        string IMigrationMetadata.Id
        {
            get { return "202104191821036_FkExpense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
